name: Check DCO

on:
  pull_request:

permissions: {}

jobs:
  check-dco:
    name: Check DCO
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: KineticCafe/actions-dco@1c23966ecce077f76671a61caabeb13eefc72a51 # v1.3.8
        with:
          exempt-authors: |
            austin@zieglers.ca
