name: Reviewdog

on:
  pull_request:

permissions: {}

jobs:
  typos:
    if: ${{ github.event.action != 'closed' }}
    name: Typos
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: reviewdog/action-typos@2d77b519f5787ca723660c00f9bc82d61b63f5fe #v1.16.0

  actionlint:
    if: ${{ github.event.action != 'closed' }}
    name: Actionlint
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: reviewdog/action-actionlint@abd537417cf4991e1ba8e21a67b1119f4f53b8e0 #v1.64.1

  credo:
    if: ${{ github.event.action != 'closed' }}
    name: Credo
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 #v1.18.2
        id: install
        with:
          otp-version: '27'
          elixir-version: '1.17'

      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2.0
        with:
          key: builds@elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}
          path: |
            deps
            _build

      - run: mix 'do' deps.get, deps.compile

      - uses: reviewdog/action-setup@3f401fe1d58fe77e10d665ab713057375e39b887 #v1.3.0

      - name: 'mix credo --strict | reviewdog'
        run: |
          mix credo suggest --strict --format=flycheck |
            reviewdog \
              -efm="%f:%l:%c: %t: %m" \
              -efm="%f:%l: %t: %m" \
              -name="credo" \
              -reporter="github-pr-check" -level="error"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
