name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: ["main"]
  pull_request:

permissions: {}

jobs:
  zizmor:
    name: zizmor latest via Cargo
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      # required for workflows in private repositories
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@ac90e63697ac2784f4ecfe2964e1a285c304003a # v1.14.1
      - name: Get zizmor
        run: cargo install --locked zizmor
      - name: Run zizmor
        run: zizmor --persona pedantic --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@2d92b76c45b91eb80fc44c74ce3fce0ee94e8f9d # v3.29.5
        with:
          sarif_file: results.sarif
          category: zizmor
